//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakerSpaceOS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembersTrainingCourse
    {
        public int TrainingCourseID { get; set; }
        public int MemberID { get; set; }
        public bool PassedCourse { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual TrainingCourse TrainingCourse { get; set; }
    }
}
