//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakerSpaceOS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.MembersTrainingCourses = new HashSet<MembersTrainingCourse>();
            this.RFIDTags = new HashSet<RFIDTag>();
        }
    
        public int MemberID { get; set; }
        public string EmailAddress { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<MembersTrainingCourse> MembersTrainingCourses { get; set; }
        public virtual ICollection<RFIDTag> RFIDTags { get; set; }
    }
}
