//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakerSpaceOS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFIDTag
    {
        public int ID { get; set; }
        public string RFIDCode { get; set; }
        public string PIN { get; set; }
        public Nullable<int> MemberID { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
